version: "2"
services:
  web:
    build: .
    volumes:
      - .:/appp
    command: node index.js ${TELEGRAM_BOT_API} ${ROOT_ID}
    ports:
    - "3000:3000"
    links:
     - mongodb
  mongodb:
     image: mongo
     ports:
       - "27017:27017"
     volumes_from:
       - mongodata
  mongodata:
    image: tianon/true
    volumes:
      - /data/db
